---
- hosts: all
  strategy: free
  become: yes
  become_method: sudo
  tasks:
   - name: Get the keytool location
     shell: "locate keytool|head -n 1"
     register: keytool

   - debug:
      msg: "{{keytool.stdout}}"
      