---
# tasks file for ans-apache
- name: "Ensure packages are present"
  yum:
    name: "{{pkgs}}"
    state: present

- name: "Ensure index.html is present"
  template:
    dest: /var/www/html/index.html
    src: index.html.j2

- name: "Ensure httpd service is enabled and started"
  service:
    name: "{{item}}"
    state: started
    enabled: true
  with_items: "{{svcs}}"

- name: "White list http in firewalld"
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true


