---
- hosts: all
  strategy: free
  become: yes
  become_method: sudo
  tasks:
   - name: Get the keytool location
     shell: "cat /opt/app/config/keystore_password.txt"
     register: keytool

   - debug:
      msg: "{{keytool.stdout}}"
      