---
- hosts: all
  strategy: free
  become: yes
  become_method: sudo
  tasks:
    - name: Get the keytool location
      shell: "locate keytool|head -n 1"
      register: keytool 
      no_log: True
    - name: Get the Keystore password 
      shell: "cat /opt/app/config/keystore_password.txt"
      register: keystore_password
      no_log: True
    - name: Validation 
      command: "{{keytool.stdout}} -list -v -keystore /opt/app/config/keystore.jks -storepass {{keystore_password.stdout}}"
      register: result
      no_log: True
    - set_fact:
         basic: "{{result.stdout_lines| select('match','^[^#,  \\t\\]\\[*00BEA]')|list}}"
      register: basic
      no_log: True
    - debug:
        msg: "{{basic|select('match','^((?! \\[).)*$') |list}}"
    
    - name: Get the heartbeat state
      shell: "/opt/deployasaurus/heartbeat verify|tail -1|cut -d ':' -f 6"
      register: heartbeat

    - debug:
        msg: "{{ansible_nodename}}:{{heartbeat.stdout}}"
    
    
      
      
      






